### PR TITLE
update test runner to use bats-assert in tests

### PR DESCRIPTION
**Pull request by glennj**
The bash tests are being updated to use the [bats-assert](https://github.com/bats-core/bats-assert) library. This gives students better feedback for failing tests. See https://github.com/exercism/bash/pull/539

This PR updates the test data to use bats-assert as well.

### CODE REVIEW

**Comment by iHiD** [comment]
Should I merge this now?

**Comment by glennj** [comment]
hang on a sec, let me check if this changes _require_ the bash track PR first.

**Comment by glennj** [comment]
It's fine, @iHiD please go ahead.

**Comment by iHiD** [comment]
Thanks :)

**Pull request merged**
